name: CI workflow

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install --only=dev
    - name: Run linter
      run: npm run linter
